// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VidaSalud.Api.Data;

#nullable disable

namespace VidaSalud.Api.Migrations
{
    [DbContext(typeof(VidaSaludDbContext))]
    [Migration("20260831163126_AddMovimientoInventario")]
    partial class AddMovimientoInventario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VidaSalud.Api.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("IdCategoria");

                    b.HasIndex("NombreCategoria")
                        .IsUnique();

                    b.ToTable("categoria", (string)null);

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            NombreCategoria = "Analgésicos"
                        },
                        new
                        {
                            IdCategoria = 2,
                            NombreCategoria = "Antibióticos"
                        },
                        new
                        {
                            IdCategoria = 3,
                            NombreCategoria = "Antiinflamatorios"
                        },
                        new
                        {
                            IdCategoria = 4,
                            NombreCategoria = "Vitaminas y Suplementos"
                        },
                        new
                        {
                            IdCategoria = 5,
                            NombreCategoria = "Antigripales"
                        },
                        new
                        {
                            IdCategoria = 6,
                            NombreCategoria = "Gastrointestinales"
                        },
                        new
                        {
                            IdCategoria = 7,
                            NombreCategoria = "Cardiovasculares"
                        },
                        new
                        {
                            IdCategoria = 8,
                            NombreCategoria = "Dermatológicos"
                        });
                });

            modelBuilder.Entity("VidaSalud.Api.Models.Lote", b =>
                {
                    b.Property<int>("IdLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_lote");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLote"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.HasKey("IdLote");

                    b.HasIndex("FechaVencimiento")
                        .HasDatabaseName("idx_lote_fecha_venc");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("idx_lote_producto");

                    b.ToTable("lote", (string)null);
                });

            modelBuilder.Entity("VidaSalud.Api.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_movimiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMovimiento"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("EstadoMovimiento")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("estado_movimiento");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("responsable");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("idx_mov_producto");

                    b.ToTable("movimiento_inventario", (string)null);
                });

            modelBuilder.Entity("VidaSalud.Api.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("idx_producto_nombre");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("VidaSalud.Api.Models.Lote", b =>
                {
                    b.HasOne("VidaSalud.Api.Models.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lote_producto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("VidaSalud.Api.Models.MovimientoInventario", b =>
                {
                    b.HasOne("VidaSalud.Api.Models.Producto", "Producto")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mov_producto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("VidaSalud.Api.Models.Producto", b =>
                {
                    b.HasOne("VidaSalud.Api.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_producto_categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("VidaSalud.Api.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("VidaSalud.Api.Models.Producto", b =>
                {
                    b.Navigation("Lotes");

                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
