// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VidaSalud.Api.Data;

#nullable disable

namespace VidaSalud.Api.Migrations
{
    [DbContext(typeof(VidaSaludDbContext))]
    partial class VidaSaludDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VidaSalud.Api.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("IdCategoria");

                    b.HasIndex("NombreCategoria")
                        .IsUnique();

                    b.ToTable("categoria", (string)null);

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            NombreCategoria = "Analgésicos"
                        },
                        new
                        {
                            IdCategoria = 2,
                            NombreCategoria = "Antibióticos"
                        },
                        new
                        {
                            IdCategoria = 3,
                            NombreCategoria = "Antiinflamatorios"
                        },
                        new
                        {
                            IdCategoria = 4,
                            NombreCategoria = "Vitaminas y Suplementos"
                        },
                        new
                        {
                            IdCategoria = 5,
                            NombreCategoria = "Antigripales"
                        },
                        new
                        {
                            IdCategoria = 6,
                            NombreCategoria = "Gastrointestinales"
                        },
                        new
                        {
                            IdCategoria = 7,
                            NombreCategoria = "Cardiovasculares"
                        },
                        new
                        {
                            IdCategoria = 8,
                            NombreCategoria = "Dermatológicos"
                        });
                });

            modelBuilder.Entity("VidaSalud.Api.Models.LogAuditoria", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_log");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accion");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("actor");

                    b.Property<string>("Detalle")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("detalle");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidad");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("integer")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_utc");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("resultado");

                    b.HasKey("IdLog");

                    b.HasIndex("FechaUtc")
                        .HasDatabaseName("idx_log_auditoria_fecha");

                    b.ToTable("log_auditoria", null, t =>
                        {
                            t.HasCheckConstraint("ck_log_auditoria_resultado", "resultado IN ('EXITOSO', 'FALLIDO', 'RECHAZADO')");
                        });
                });

            modelBuilder.Entity("VidaSalud.Api.Models.Lote", b =>
                {
                    b.Property<int>("IdLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_lote");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLote"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.HasKey("IdLote");

                    b.HasIndex("FechaVencimiento")
                        .HasDatabaseName("idx_lote_fecha_venc");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("idx_lote_producto");

                    b.ToTable("lote", null, t =>
                        {
                            t.HasCheckConstraint("ck_lote_cantidad", "cantidad >= 0");
                        });
                });

            modelBuilder.Entity("VidaSalud.Api.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_movimiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMovimiento"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("EstadoMovimiento")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("estado_movimiento");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("responsable");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("idx_mov_producto");

                    b.ToTable("movimiento_inventario", null, t =>
                        {
                            t.HasCheckConstraint("ck_movimiento_cantidad", "cantidad > 0");

                            t.HasCheckConstraint("ck_movimiento_estado", "estado_movimiento IN ('REGISTRADO')");

                            t.HasCheckConstraint("ck_movimiento_tipo", "tipo_movimiento IN ('ENTRADA', 'SALIDA')");
                        });
                });

            modelBuilder.Entity("VidaSalud.Api.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("idx_producto_nombre");

                    b.ToTable("producto", null, t =>
                        {
                            t.HasCheckConstraint("ck_producto_precio", "precio >= 0");
                        });
                });

            modelBuilder.Entity("VidaSalud.Api.Models.SolicitudBaja", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitud");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_resolucion");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_solicitud");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("motivo");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("ResueltaPor")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("resuelta_por");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_solicitud_baja_estado");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("idx_solicitud_baja_usuario_pendiente")
                        .HasFilter("estado = 'PENDIENTE'");

                    b.ToTable("solicitud_baja", null, t =>
                        {
                            t.HasCheckConstraint("ck_solicitud_baja_estado", "estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')");
                        });
                });

            modelBuilder.Entity("VidaSalud.Api.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_usuario_email");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("idx_usuario_nombre_usuario");

                    b.ToTable("usuario", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuario_rol", "rol IN ('ADMINISTRADOR', 'ENCARGADO', 'AUXILIAR')");
                        });
                });

            modelBuilder.Entity("VidaSalud.Api.Models.Lote", b =>
                {
                    b.HasOne("VidaSalud.Api.Models.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lote_producto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("VidaSalud.Api.Models.MovimientoInventario", b =>
                {
                    b.HasOne("VidaSalud.Api.Models.Producto", "Producto")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mov_producto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("VidaSalud.Api.Models.Producto", b =>
                {
                    b.HasOne("VidaSalud.Api.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_producto_categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("VidaSalud.Api.Models.SolicitudBaja", b =>
                {
                    b.HasOne("VidaSalud.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_solicitud_baja_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VidaSalud.Api.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("VidaSalud.Api.Models.Producto", b =>
                {
                    b.Navigation("Lotes");

                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
