-- VidaSalud — referencia SQL del modelo implementado al cierre del MVP.
-- La fuente ejecutable oficial son las migraciones de backend/VidaSalud.Api/Migrations.

CREATE TABLE categoria (
    id_categoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria varchar(50) NOT NULL UNIQUE
);

CREATE TABLE producto (
    id_producto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100) NOT NULL UNIQUE,
    id_categoria integer NOT NULL,
    precio numeric(10,2) NOT NULL,
    fecha_creacion date NOT NULL,
    CONSTRAINT ck_producto_precio CHECK (precio >= 0),
    CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria)
        REFERENCES categoria(id_categoria) ON DELETE RESTRICT
);

CREATE TABLE lote (
    id_lote integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto integer NOT NULL,
    cantidad integer NOT NULL,
    fecha_ingreso date NOT NULL,
    fecha_vencimiento date NOT NULL,
    CONSTRAINT ck_lote_cantidad CHECK (cantidad >= 0),
    CONSTRAINT fk_lote_producto FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto) ON DELETE CASCADE
);

CREATE TABLE movimiento_inventario (
    id_movimiento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto integer NOT NULL,
    tipo_movimiento varchar(10) NOT NULL,
    cantidad integer NOT NULL,
    fecha timestamptz NOT NULL,
    estado_movimiento varchar(15) NOT NULL,
    responsable varchar(80) NOT NULL,
    CONSTRAINT ck_movimiento_tipo CHECK (tipo_movimiento IN ('ENTRADA', 'SALIDA')),
    CONSTRAINT ck_movimiento_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_movimiento_estado CHECK (estado_movimiento IN ('REGISTRADO')),
    CONSTRAINT fk_mov_producto FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto) ON DELETE RESTRICT
);

CREATE TABLE usuario (
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(80) NOT NULL,
    nombre_usuario varchar(50) NOT NULL UNIQUE,
    email varchar(100) UNIQUE,
    rol varchar(20) NOT NULL,
    password_hash varchar(500) NOT NULL,
    fecha_registro timestamptz NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    eliminado boolean NOT NULL DEFAULT false,
    CONSTRAINT ck_usuario_rol CHECK (rol IN ('ADMINISTRADOR', 'ENCARGADO', 'AUXILIAR'))
);

CREATE TABLE solicitud_baja (
    id_solicitud integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario integer,
    nombre_usuario varchar(50) NOT NULL,
    motivo varchar(250),
    estado varchar(15) NOT NULL,
    fecha_solicitud timestamptz NOT NULL,
    fecha_resolucion timestamptz,
    resuelta_por varchar(80),
    CONSTRAINT ck_solicitud_baja_estado
        CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')),
    CONSTRAINT fk_solicitud_baja_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario) ON DELETE SET NULL
);

CREATE TABLE log_auditoria (
    id_log integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor varchar(80) NOT NULL,
    accion varchar(50) NOT NULL,
    entidad varchar(50) NOT NULL,
    entidad_id integer,
    fecha_utc timestamptz NOT NULL,
    resultado varchar(15) NOT NULL,
    detalle varchar(250),
    CONSTRAINT ck_log_auditoria_resultado
        CHECK (resultado IN ('EXITOSO', 'FALLIDO', 'RECHAZADO'))
);

CREATE INDEX idx_producto_nombre ON producto(nombre);
CREATE INDEX idx_lote_producto ON lote(id_producto);
CREATE INDEX idx_lote_fecha_venc ON lote(fecha_vencimiento);
CREATE INDEX idx_mov_producto ON movimiento_inventario(id_producto);
CREATE INDEX idx_solicitud_baja_estado ON solicitud_baja(estado);
CREATE UNIQUE INDEX idx_solicitud_baja_usuario_pendiente
    ON solicitud_baja(id_usuario) WHERE estado = 'PENDIENTE';
CREATE INDEX idx_log_auditoria_fecha ON log_auditoria(fecha_utc);
